# Generated by Django 4.2.19 on 2025-04-03 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0003_remove_salao_cliente_owner_is_superuser_and_more"),
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="salao",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="admin_panel.salao",
            ),
        ),
    ]
