# Generated by Django 4.2.19 on 2025-04-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="is_salao",
            field=models.BooleanField(default=False),
        ),
    ]
