# Generated by Django 4.2.19 on 2025-04-01 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0002_cliente_is_salao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="is_salao",
        ),
    ]
