# Generated by Django 4.2.19 on 2025-04-01 18:06

import admin_panel.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_master", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("objects", admin_panel.models.OwnerManager()),
            ],
        ),
        migrations.CreateModel(
            name="Salao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "cnpj",
                    models.CharField(blank=True, max_length=18, null=True, unique=True),
                ),
                ("endereco", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ativo", "Ativo"), ("inativo", "Inativo")],
                        default="ativo",
                        max_length=10,
                    ),
                ),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
                (
                    "proprietario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_panel.owner",
                    ),
                ),
            ],
        ),
    ]
