# Generated by Django 4.2.19 on 2025-04-03 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("admin_panel", "0001_initial"),
        ("clientes", "0001_initial"),
        ("agendamentos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="salao",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saloes",
                to="clientes.cliente",
            ),
        ),
        migrations.AddField(
            model_name="salao",
            name="proprietario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="pagamento",
            name="agendamento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="agendamentos.agendamento",
            ),
        ),
    ]
