# Generated by Django 4.2.19 on 2025-04-05 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("saloes", "0001_initial"),
        ("admin_panel", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagamento",
            name="salao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="saloes.salao"
            ),
        ),
    ]
