# Generated by Django 4.2.19 on 2025-04-03 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clientes", "0001_initial"),
        ("admin_panel", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salao",
            name="cliente",
        ),
        migrations.AddField(
            model_name="owner",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pagamento",
            name="salao",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="admin_panel.salao",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="salao",
            name="clientes",
            field=models.ManyToManyField(
                related_name="saloes_cliente", to="clientes.cliente"
            ),
        ),
        migrations.AlterField(
            model_name="pagamento",
            name="metodo",
            field=models.CharField(
                choices=[
                    ("pix", "PIX"),
                    ("cartao", "Cartão de Crédito/Débito"),
                    ("dinheiro", "Dinheiro"),
                    ("boleto", "Boleto"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="salao",
            name="proprietario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saloes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
