# Generated by Django 4.2.19 on 2025-04-03 15:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0003_remove_salao_cliente_owner_is_superuser_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagamento",
            name="data_pagamento",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
