# Generated by Django 4.2.19 on 2025-04-03 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0004_alter_pagamento_data_pagamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagamento",
            name="data_pagamento",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
