# Generated by Django 4.2.19 on 2025-04-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0005_alter_pagamento_data_pagamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salao",
            name="cnpj",
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
    ]
