# Generated by Django 4.2.19 on 2025-04-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0006_alter_salao_cnpj"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salao",
            name="estado",
        ),
        migrations.AlterField(
            model_name="salao",
            name="status",
            field=models.CharField(
                choices=[
                    ("ativo", "Ativo"),
                    ("inativo", "Inativo"),
                    ("suspenso", "Suspenso"),
                ],
                default="ativo",
                max_length=10,
            ),
        ),
    ]
