# Generated by Django 4.2.19 on 2025-04-04 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0008_alter_status_field"),
    ]

    operations = []
