# Generated by Django 4.2.19 on 2025-04-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0010_alter_salao_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salao",
            name="status",
            field=models.CharField(
                choices=[
                    ("ativo", "Ativo"),
                    ("inativo", "Inativo"),
                    ("suspenso", "Suspenso"),
                ],
                default="ativo",
                max_length=30,
            ),
        ),
    ]
