# Generated by Django 4.2.19 on 2025-04-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0012_alter_salao_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="salao",
            name="estado",
            field=models.CharField(default="SP", max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="salao",
            name="status",
            field=models.CharField(
                choices=[("ativo", "Ativo"), ("inativo", "Inativo")],
                default="ativo",
                max_length=7,
            ),
        ),
    ]
