# Generated by Django 4.2.19 on 2025-04-04 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0013_salao_estado_alter_salao_status"),
    ]

    operations = []
