# Generated by Django 4.2.19 on 2025-04-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agendamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_hora", models.DateTimeField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("status", models.CharField(default="agendado", max_length=20)),
            ],
        ),
    ]
