# Generated by Django 4.2.19 on 2025-04-05 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agendamentos", "0001_initial"),
        ("clientes", "0001_initial"),
        ("admin_panel", "0003_initial"),
        ("saloes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="clientes.cliente"
            ),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="salao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="saloes.salao"
            ),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="servico",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="admin_panel.servico"
            ),
        ),
    ]
