# Generated by Django 4.2.19 on 2025-04-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamentos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="valor",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
