# Generated by Django 4.2.19 on 2025-04-01 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0005_salao"),
        ("agendamentos", "0002_agendamento_valor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agendamento",
            name="criado_em",
        ),
        migrations.RemoveField(
            model_name="agendamento",
            name="servico",
        ),
        migrations.AddField(
            model_name="agendamento",
            name="salao",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="clientes.salao",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="clientes.cliente"
            ),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="status",
            field=models.CharField(default="agendado", max_length=20),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="valor",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
